language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
    - os: osx
      compiler: clang

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi

install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install qt58base qt58x11extras qt58tools qt58multimedia libpulse-dev; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install qt; fi

before_script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then source /opt/qt58/bin/qt58-env.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export QTDIR="/usr/local/opt/qt"; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export PATH="$QTDIR/bin:$PATH"; fi

script:
  - qmake
  - make

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "fsstudio"
  skip_cleanup: true
