os: Visual Studio 2015

install:
  - git submodule update --init --recursive
  - set QTDIR=C:\Qt\5.8\msvc2015_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake fsstudio.pro
  - nmake /f Makefile.$env:CONFIGURATION

after_build:
  - ps: |
      $ZIP_BASE = "fsstudio-VC-$env:PLATFORM-$env:CONFIGURATION"
      $ZIP_FILE = "$($ZIP_BASE).zip"
      md $ZIP_BASE
      Copy-Item -Path $env:CONFIGURATION\FSStudio.exe -Destination $ZIP_BASE\
      Copy-Item -Path README.md -Destination $ZIP_BASE\README.txt
      If ($env:CONFIGURATION -Like "Release") {
        $QT_SUFFIX = ".dll"
      } Else {
        $QT_SUFFIX = "d.dll"
      }
      Copy-Item -Path $env:QTDIR\Qt5Core$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\Qt5Gui$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\Qt5Multimedia$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\Qt5Network$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\Qt5Widgets$QT_SUFFIX -Destination $ZIP_BASE\
      7z a $ZIP_FILE $ZIP_BASE\*
      Push-AppveyorArtifact $ZIP_FILE
