os: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - if "%platform%" == "x86" call set QTDIR=C:\Qt\5.8\msvc2015
  - if "%platform%" == "x64" call set QTDIR=C:\Qt\5.8\msvc2015_64
  - if "%platform%" == "x86" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%platform%" == "x64" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake fsstudio.pro
  - nmake /f Makefile.%CONFIGURATION%

after_build:
  - ps: |
      $ZIP_BASE = "fsstudio-VC-$env:PLATFORM-$env:CONFIGURATION"
      $ZIP_FILE = "$($ZIP_BASE).zip"
      md $ZIP_BASE
      Copy-Item -Path $env:CONFIGURATION\FSStudio.exe -Destination $ZIP_BASE\
      Copy-Item -Path README.md -Destination $ZIP_BASE\README.txt
      If ($env:CONFIGURATION -Like "Release") {
        $QT_SUFFIX = ".dll"
      } Else {
        $QT_SUFFIX = "d.dll"
      }
      Copy-Item -Path $env:QTDIR\bin\Qt5Core$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\bin\Qt5Gui$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\bin\Qt5Multimedia$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\bin\Qt5Network$QT_SUFFIX -Destination $ZIP_BASE\
      Copy-Item -Path $env:QTDIR\bin\Qt5Widgets$QT_SUFFIX -Destination $ZIP_BASE\
      7z a $ZIP_FILE $ZIP_BASE\*
      Push-AppveyorArtifact $ZIP_FILE
