name: windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        buildtype: [Debug, Release]
        architecture: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}

      - name: Install dependencies
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.2.0'
          host: 'windows'
          target: 'desktop'
          arch: "win64_msvc2019_64"
          cache: true
        
      - name: Configure FSStudio
        run: |
          cmake -B build -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }}

      - name: Build FSStudio
        shell: bash
        run: |
          cd build
          nmake

      - name: Pack FSStudio
        shell: bash
        run: |
          cd build
          nmake package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FSStudio-${{ matrix.architecture }}-${{ matrix.buildtype }}
          path: ./build/FSStudio-${{ matrix.architecture }}-${{ matrix.buildtype }}.exe
